### ISSUE TITLE
TypeError: Buffer.alloc is not a function

### ISSUE THREAD

**Issue by kbmetz** [fabiospampinato/cliflix#10]
Ubuntu 16.04

#node --version
v4.2.6

 watch
/usr/local/lib/node_modules/@fabiospampinato/watch/node_modules/parse-torrent/index.js:110
;(function () { Buffer.alloc(0) })()
                       ^

TypeError: Buffer.alloc is not a function
    at /usr/local/lib/node_modules/@fabiospampinato/watch/node_modules/parse-torrent/index.js:110:24
    at Object.<anonymous> (/usr/local/lib/node_modules/@fabiospampinato/watch/node_modules/parse-torrent/index.js:110:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@fabiospampinato/watch/dist/index.js:40:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@fabiospampinato/watch/dist/cli.js:44:10)

**Comment by fabiospampinato** [comment]
You've got to update node to version 6.0.0 or more, unfortunately we don't support lower versions than that.
