### ISSUE TITLE
Invalid torrent identifier

### ISSUE THREAD

**Issue by stjepangolemac** [fabiospampinato/cliflix#18]
I get this for every torrent I pick:

```
(node:10754) Warning: N-API is an experimental feature and could change at any time.
Error: Invalid torrent identifier

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.11.0, webtorrent 0.102.4, node v8.11.3, darwin x64, exit 1
(node:10749) UnhandledPromiseRejectionWarning: Error: null
    at Function.module.exports.sync (/Users/stjepangolemac/.config/yarn/global/node_modules/execa/index.js:303:26)
    at Object.<anonymous> (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:202:23)
    at step (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:33:23)
    at Object.next (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:14:53)
    at /Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:4:12)
    at Object.stream (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:194:16)
    at Object.<anonymous> (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:104:33)
    at step (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:33:23)
    at Object.next (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:14:53)
    at fulfilled (/Users/stjepangolemac/.config/yarn/global/node_modules/cliflix/dist/index.js:5:58)
    at <anonymous>
(node:10749) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10749) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fabiospampinato** [comment]
What torrent provider are you using? Can you try the others so that we can check if specific providers are not working?

**Comment by stjepangolemac** [comment]
Ok so tpb cannot find anything, 1337to is actually crashing the app and rarbg is working.

**Comment by fabiospampinato** [comment]
Thanks for the info! TPB might be blocked by your ISP. There might be a bug in the library the provides us search results from 1337x, I'll look into that.

**Comment by fabiospampinato** [comment]
It should be fixed now, thanks.
