### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by kamil98** [fabiospampinato/cliflix#20]
After fresh installation on osx 10.4:

```bash
MacBook-Pro-Kamil:~ kamil$ cliflix
/usr/local/lib/node_modules/cliflix/node_modules/torrent-search-api/lib/TorrentProvider.js:240
    return req({ ...opts, followRedirect: false }).then(response => {
                 ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/cliflix/node_modules/torrent-search-api/lib/ProviderManager.js:4:25)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

**Comment by fabiospampinato** [comment]
You need node >= 6.
